import { faker } from "@faker-js/faker"
import { prisma } from "../../src/config/prisma"

interface ProductData {
    name: string
    description: string
    sku: string
    weight: number // in grams
}

class ProductsFactory {
    private productsByCategory: Record<string, ProductData[]> = {
        'Fruits': [
            { name: 'Granny Smith Apple 500g', description: 'Crisp and refreshingly tart Granny Smith apples, sourced from premium orchards. Each apple is hand-picked at peak ripeness to ensure maximum flavor and juiciness. Rich in dietary fiber, vitamin C, and antioxidants, these apples are perfect for snacking, baking, or adding to salads. Store in a cool, dry place or refrigerate to maintain freshness.', sku: 'FRT-APPLE-GRANY-500G', weight: 500 },
            { name: 'Sunpride Cavendish Banana 1kg', description: 'Sweet and naturally ripened Cavendish bananas from the Sunpride farms. These premium bananas are packed with potassium, dietary fiber, and natural sugars for an instant energy boost. Great for breakfast, smoothies, or desserts. Each bunch contains approximately 5-7 fingers and is harvested at the optimal ripeness. Best consumed within 3-5 days of purchase.', sku: 'FRT-BNNA-CAVEN-1KG', weight: 1000 },
            { name: 'Sunkist Navel Orange 1kg', description: 'Premium Sunkist Navel Oranges, known for their seedless flesh and easy-to-peel skin. Each orange bursts with naturally sweet citrus juice loaded with vitamin C, folate, and potassium. These oranges are grown in sun-drenched groves, giving them their signature vibrant color and rich flavor. Ideal for juicing, snacking, or adding a citrusy twist to your cooking.', sku: 'FRT-ORNG-NAVL-1KG', weight: 1000 },
            { name: 'Driscoll\'s Strawberry 250g', description: 'Driscoll\'s premium strawberries — the world\'s finest berries. Each berry is carefully hand-selected for consistent size, vibrant red color, and exceptional sweetness. High in antioxidants, vitamin C, and manganese, these strawberries are wonderful eaten fresh, added to yogurt, blended into smoothies, or used in desserts. Keep refrigerated and consume within 2-3 days for best flavor.', sku: 'FRT-STRW-DRSC-250G', weight: 250 },
            { name: 'Thompson Seedless Grape 500g', description: 'Crisp and juicy Thompson Seedless grapes, perfect for snacking right off the bunch. These premium grapes are naturally sweet with a mild, refreshing flavor and thin, tender skin. Rich in resveratrol, vitamin K, and antioxidants that support heart health. Excellent for fruit platters, salads, or freezing for a cool summer treat. Keep refrigerated and rinse before eating.', sku: 'FRT-GRPE-THMP-500G', weight: 500 },
            { name: 'Del Monte Gold Pineapple 1pc', description: 'A whole Del Monte Gold Extra Sweet Pineapple, recognized worldwide for its distinctly golden color and exceptional sweetness. This tropical gem is cultivated in the rich volcanic soils of Hawaii and Latin America, resulting in a flavor that\'s less acidic and far sweeter than regular pineapples. Packed with bromelain enzyme, vitamin C, and manganese. Perfect for fresh eating, grilling, or blending into tropical drinks.', sku: 'FRT-PINE-DLMG-1PC', weight: 1200 },
            { name: 'Harum Manis Mango 500g', description: 'Premium Harum Manis (Arumanis) mangoes, the most coveted variety in Indonesia and Southeast Asia. These mangoes are celebrated for their intensely fragrant aroma, silky-smooth flesh, and exceptionally sweet taste with virtually no fibrous texture. Harvested from mature trees in East Java, each fruit is a product of careful cultivation. Rich in vitamins A, C, and B6, folate, and fiber. Eat fresh, blend into lassi, or use as a topping for desserts.', sku: 'FRT-MNGO-HRMA-500G', weight: 500 },
            { name: 'Alpukat Mentega Avocado 500g', description: 'Premium Alpukat Mentega (Butter Avocado), the richest and most creamy variety of avocado grown in Indonesia. Known for its smooth, buttery texture and mild, nutty flavor, this variety is prized by chefs and health enthusiasts alike. Each avocado is loaded with heart-healthy monounsaturated fats, potassium, folate, and vitamins K, C, B5, and B6. Ideal for guacamole, avocado toast, smoothies, or eating plain with a pinch of salt.', sku: 'FRT-AVCD-MINT-500G', weight: 500 },
        ],
        'Vegetables': [
            { name: 'Baby Carrot Multipack 400g', description: 'Sweet and crunchy baby carrots, pre-washed and ready to eat right from the bag. Grown in fertile soils and harvested young for maximum tenderness and natural sweetness, these carrots are a nutritional powerhouse. Rich in beta-carotene, vitamin K1, potassium, and antioxidants. A perfect healthy snack for kids and adults. Great for crudités, salads, soups, stir-fries, and juicing. Keep refrigerated.', sku: 'VEG-CRRT-BABY-400G', weight: 400 },
            { name: 'Brocoli Premium Segar 500g', description: 'Fresh premium broccoli crowns, harvested at peak maturity for the best flavor and nutritional value. This nutrient-dense cruciferous vegetable is among the most studied foods in nutritional science, packed with vitamin C, vitamin K, folate, fiber, and a range of powerful antioxidants including sulforaphane. Excellent steamed, roasted, blanched, or added to pasta, stir-fries, and casseroles. Refrigerate and use within 5-7 days.', sku: 'VEG-BROC-PREM-500G', weight: 500 },
            { name: 'Bayam Organik Segar 200g', description: 'Certified organic fresh spinach leaves, washed and packed at the source for maximum freshness. These tender leaves are grown without synthetic pesticides or fertilizers, making them an ideal choice for health-conscious shoppers. Spinach is one of the most nutrient-rich vegetables on earth, containing iron, calcium, magnesium, vitamin K, vitamin A, and a spectrum of antioxidants. Use raw in salads, sauté with garlic, blend into green smoothies, or add to pasta and omelets.', sku: 'VEG-SPCH-ORG-200G', weight: 200 },
            { name: 'Tomat Cherry Premium 300g', description: 'Premium Cherry Tomatoes in a convenient resealable punnet. These bite-sized tomatoes burst with an intensely sweet and tangy flavor far superior to larger tomato varieties. Vine-ripened under the sun for maximum taste, they are exceptionally high in lycopene, an antioxidant linked to reduced risk of heart disease and cancer. Rich in vitamins C and K, potassium, and folate. Perfect for salads, pasta dishes, roasting, or simply snacking.', sku: 'VEG-TOMT-CHRY-300G', weight: 300 },
            { name: 'Mentimun Jepang 500g', description: 'Premium Japanese Cucumbers (Kyuri), prized for their thin skin, crisp texture, minimal seeds, and refreshing mild flavor. These cucumbers are grown in controlled greenhouse environments to ensure consistent quality and are virtually bitterness-free. Excellent hydrating foods due to their high water content (over 95%). Rich in vitamin K and antioxidants. Ideal for fresh salads, pickling, sushi rolls, or as a cool snack with dipping sauce.', sku: 'VEG-CUCM-JPN-500G', weight: 500 },
            { name: 'Paprika Tricolor Mix 300g', description: 'A vibrant trio of red, yellow, and green bell peppers in one convenient pack. Bell peppers are among the richest sources of vitamin C (especially red peppers, which contain three times the vitamin C of an orange) and are also rich in vitamin B6, vitamin A, folate, and various antioxidants. Their sweet, crisp flesh is perfect for stir-fries, roasted vegetable medleys, stuffed pepper dishes, or sliced raw for snacking. Low in calories, zero fat.', sku: 'VEG-PPKR-TRIO-300G', weight: 300 },
            { name: 'Bawang Bombay Kuning 500g', description: 'Premium Yellow Onions — the backbone of countless cuisines around the world. These robust onions have a firm, paper-like golden skin and a pungent, sharp flavor when raw that sweetens dramatically when cooked. Rich in quercetin, a flavonoid with anti-inflammatory properties, and also containing vitamin C, B vitamins, and potassium. Essential for curries, soups, stews, sauces, and as a flavor base for virtually every savory dish. Store in a cool, dark, well-ventilated place.', sku: 'VEG-ONON-YLWB-500G', weight: 500 },
            { name: 'Kentang Dieng Premium 1kg', description: 'Premium Dieng Plateau potatoes from Central Java, grown at 2000 meters above sea level in cool volcanic soil that gives them their signature fluffy interior and rich, earthy flavor. These potatoes are incredibly versatile — boil, bake, roast, mash, or fry them for dramatically different textures and flavors. A good source of potassium, vitamin C, vitamin B6, and dietary fiber. They are also naturally gluten-free and fat-free in their raw state. Store away from light to prevent greening.', sku: 'VEG-POTO-DING-1KG', weight: 1000 },
        ],
        'Dairy': [
            { name: 'Ultra Milk Full Cream 1L', description: 'Ultra Milk Full Cream is Indonesia\'s most trusted pasteurized full cream milk, delivering a rich, creamy taste that has been a family staple for generations. Made from fresh, high-quality milk and processed using Ultra High Temperature (UHT) pasteurization, it retains all the natural goodness and extends shelf life without preservatives. Packed with calcium, protein, vitamin D, and essential B vitamins to support bone health, muscle function, and overall nutrition. Perfect for drinking cold, warming up, pouring over cereal, or using in baking and cooking.', sku: 'DRY-MILK-ULTR-1LTR', weight: 1030 },
            { name: 'Anchor Cheddar Cheese Block 250g', description: 'Anchor Cheddar Cheese, crafted in New Zealand using milk from pasture-fed cows. New Zealand\'s lush green pastures and temperate climate produce milk with an exceptional natural richness, resulting in a cheddar with a full-bodied, slightly sharp flavor and smooth, firm texture. Naturally matured for a balanced taste, this block cheddar is perfect for slicing onto sandwiches and crackers, melting into sauces, or topping burgers and pizzas. Rich in calcium and protein. Refrigerate after opening.', sku: 'DRY-CHDR-ANCR-250G', weight: 250 },
            { name: 'Yummy Greek Yogurt Plain 500g', description: 'Thick, creamy Greek-style yogurt made from locally sourced fresh milk, strained multiple times for an indulgently rich texture. Compared to regular yogurt, this Greek yogurt contains twice the protein, fewer carbohydrates, and a delightfully tangy flavor. Each serving is packed with live probiotic cultures (L. acidophilus, L. bifidus) that support digestive health and boost immunity. Enjoy it plain, with honey and granola, blended into smoothies, or as a healthy substitute for sour cream and mayonnaise.', sku: 'DRY-YOGT-GRPN-500G', weight: 500 },
            { name: 'Anchor Unsalted Butter 227g', description: 'Premium Anchor Unsalted Butter, made from 100% pure cream sourced from New Zealand\'s free-range, pasture-fed cows. Unlike blended or margarine-based spreads, this butter contains no vegetable oils, additives, or artificial flavors — just pure, natural cream churned to perfection. Its clean, rich dairy flavor makes it the preferred choice of bakers and professional chefs worldwide. Use for baking cakes, cookies, and pastries, or as a finishing butter for sauces, sautéed vegetables, and pan-seared proteins. Refrigerate after opening.', sku: 'DRY-BUTR-ANUN-227G', weight: 227 },
            { name: 'Telur Ayam Kampung Omega 10pcs', description: 'Free-range Kampung (village) eggs enriched with Omega-3 fatty acids, sourced from native Indonesian chickens fed a natural diet. Unlike conventional eggs, Kampung eggs have significantly smaller yolks, richer color, and a more intense, robust flavor — a sign of superior nutritional content. Each egg is naturally higher in vitamins A, D, and E, and contains a better omega-3 to omega-6 ratio compared to cage-grown eggs. Pack of 10 freshly collected eggs. Best before date stamped on carton. Keep refrigerated below 10°C.', sku: 'DRY-EGGC-KMPG-10PC', weight: 600 },
            { name: 'Kiri Cream Cheese Spread 200g', description: 'Kiri is a beloved premium cream cheese spread made in France by the renowned Bel Group. Known globally for its signature mild flavor and incredibly smooth, spreadable texture, Kiri melts in the mouth and pairs beautifully with everything from bagels and toast to fresh fruit and crackers. Made with fresh pasteurized milk and cream, it contains no artificial flavors or preservatives. Also excellent as a base for cheesecakes, dips, and savory sauces. Refrigerate and consume within 5 days of opening.', sku: 'DRY-CRMC-KIRI-200G', weight: 200 },
            { name: 'Diamond Sour Cream 225g', description: 'Diamond Sour Cream is a premium cultured cream product with a characteristically rich, tangy flavor and thick, velvety texture. Made from pasteurized fresh cream fermented with active lactic acid bacteria cultures, it is an essential ingredient in Tex-Mex cuisines, Eastern European cooking, and baking. Use it as a topping for baked potatoes, nachos, and tacos, stir into soups and sauces, or incorporate it into cakes and muffins for incredible moisture and a subtle tang. Store refrigerated.', sku: 'DRY-SRCM-DIAM-225G', weight: 225 },
            { name: 'Greenfields Low-Fat Cottage Cheese 250g', description: 'Greenfields Low-Fat Cottage Cheese — a fresh, unaged cheese with a mild, creamy flavor and distinctive soft, curd-like texture. One of the most protein-dense dairy products available, a single serving provides approximately 14g of slow-digesting casein protein, making it an excellent pre-bedtime snack for muscle recovery. Naturally low in fat and calories while high in selenium, B vitamins, and phosphorus. Wonderful eaten plain with fruit and nuts, used in savory dips, or as a ricotta substitute in lasagna and stuffed pasta.', sku: 'DRY-CTCH-GRFL-250G', weight: 250 },
        ],
        'Meat & Poultry': [
            { name: 'Dada Ayam Broiler Tanpa Tulang 500g', description: 'Premium boneless, skinless chicken breast from Grade A broiler chickens raised in certified farms under strict hygiene and welfare standards. The breast is the leanest cut of the chicken, providing an exceptional protein-to-fat ratio — approximately 31g of protein and less than 4g of fat per 100g serving. Its mild, neutral flavor makes it incredibly versatile: grill it with herbs, bake with lemon, slice for stir-fries, poach for salads, or bread and pan-fry for schnitzel. Freshly processed and chilled. Keep refrigerated; use within 2 days or freeze.', sku: 'MPT-CHKB-BRST-500G', weight: 500 },
            { name: 'Daging Giling Sapi Lokal 500g', description: 'Fresh ground beef made from locally raised beef cattle, ground with a balanced fat-to-lean ratio of approximately 80:20 for maximum flavor and juiciness. This versatile minced meat is the foundation of countless beloved dishes — use it for Indonesian mie ayam and bakso, bolognese sauce, burger patties, meatballs, stuffed capsicums, or shepherd\'s pie. High in protein, iron, zinc, and vitamin B12. Packaged fresh in a vacuum-sealed tray. Keep refrigerated and use within 1-2 days; alternatively, freeze immediately for up to 3 months.', sku: 'MPT-BEEF-GRND-500G', weight: 500 },
            { name: 'Pork Loin Chops Fresh 400g', description: 'Premium fresh pork loin chops, bone-in, cut to approximately 2cm thickness for ideal cooking. Pork loin is one of the most tender and flavorful cuts, with a thin fat cap that bastes the meat during cooking, keeping it moist and juicy. These chops are sourced from select pork farms adhering to food safety standards. High in protein, thiamine (B1), selenium, zinc, and niacin. Excellent grilled over charcoal, pan-seared with a mustard crust, oven-baked with herbs, or braised in a savory sauce.', sku: 'MPT-PORK-LNCH-400G', weight: 400 },
            { name: 'So Good Turkey Beef Bacon 185g', description: 'So Good Turkey Beef Bacon — a halal-certified, lower-fat alternative to traditional pork bacon. Made from a blend of premium turkey and beef, this bacon is seasoned and smoked using natural wood smoke for an authentic smoky, savory flavor. Each strip contains significantly less fat and calories than conventional bacon while delivering the same satisfying crispy texture when pan-fried or grilled. Excellent in sandwiches, wraps, omelets, pasta carbonara, and as a topping for salads and burgers.', sku: 'MPT-BCNS-SGOD-185G', weight: 185 },
            { name: 'Salmon Fillet Segar Norway 300g', description: 'Premium Norwegian Atlantic Salmon fillet, skin-on, sustainably sourced from certified Norwegian aquaculture farms in the pristine fjords. Norwegian salmon is prized worldwide for its exceptional fat marbling, vibrant pink-orange color, and rich, buttery flavor. Loaded with heart-healthy omega-3 fatty acids (EPA and DHA), high-quality complete protein, astaxanthin, vitamin D, vitamin B12, and selenium. Eat it raw as sashimi or sushi (sushi-grade), pan-sear with butter and capers, bake with dill and lemon, or poach in court-bouillon. Fresh; consume within 24 hours or freeze.', sku: 'MPT-SALM-NRWY-300G', weight: 300 },
            { name: 'Daging Sapi Sirloin Premium 300g', description: 'Premium Sirloin Beef Steak, cut 2.5cm thick from the short loin of choice-grade cattle. Sirloin sits adjacent to the tenderloin and offers a superb balance between tenderness and robust, beefy flavor — more intensely flavorful than eye fillet yet more tender than rump. Well-marbled with intramuscular fat for juiciness and is naturally rich in creatine, zinc, iron, and complete protein (26g per 100g). Best cooked to medium-rare or medium. Pan-sear with butter, garlic, and thyme, or grill over high heat. Rest for 5 minutes before cutting.', sku: 'MPT-BEEF-SLRN-300G', weight: 300 },
            { name: 'Paha Ayam Broiler Tulang 1kg', description: 'Bone-in, skin-on chicken thighs from premium broiler chickens — widely regarded by chefs as the most flavorful part of the chicken. The thigh\'s higher fat content compared to the breast means it stays moist and juicy even if slightly overcooked, making it the most forgiving cut to cook with. Ideal for roasting, braising, frying (ayam goreng), or grilling. Exceptionally versatile in Indonesian cooking: use for opor ayam, rendang ayam, ayam bakar, or soto ayam. High in protein, iron, and zinc.', sku: 'MPT-CHKB-THGH-1KGR', weight: 1000 },
            { name: 'Iga Domba New Zealand 400g', description: 'Premium New Zealand Lamb Rib Chops (Frenched), sourced from renowned New Zealand grass-fed lamb — the global benchmark for lamb quality. These perfectly frenched rib chops are elegant, flavorful, and impressively presented, making them a centerpiece for special dinners. New Zealand lamb has a milder, sweeter flavor than other lamb due to the animals\' exclusive grass-fed diet and extensive outdoor roaming. Rich in protein, iron, zinc, and vitamin B12. Pan-sear in a hot cast iron or grill over charcoal; pair with rosemary, garlic, and a red wine jus.', sku: 'MPT-LAMB-RCHP-400G', weight: 400 },
        ],
        'Bakery': [
            { name: 'Wonder White Sandwich Bread 400g', description: 'Wonder White Sandwich Bread — soft, fluffy, and made with enriched wheat flour for a consistent, uniform crumb ideal for sandwiches, toast, and French toast. Each slice is perfectly sized with a clean, neutral flavor that lets your fillings shine. Fortified with essential vitamins and minerals including iron, thiamine, niacin, and folic acid. A staple in households across the country for generations. Individually wrapped to stay fresh longer. Best consumed before the best-before date printed on the bag; store in a cool, dry place.', sku: 'BKR-BRDW-WOND-400G', weight: 400 },
            { name: 'La Vie Butter Croissant 6pcs', description: 'Authentic French-style butter croissants from La Vie Bakery, crafted using the classic laminated dough technique: butter is folded into the dough dozens of times to create hundreds of whisper-thin, flaky layers. When baked, the water in the butter creates steam that puffs each layer, resulting in a croissant with an audibly shattering crust and a tender, honeycomb interior. Made with premium Breton butter (82% fat content), unbleached flour, and no artificial additives. Warm briefly in the oven for the ultimate experience. Pack of 6.', sku: 'BKR-CRSS-LAVB-6PCS', weight: 360 },
            { name: 'American Classic Choco Chip Cookies 180g', description: 'Classic American-style chocolate chip cookies, made with real Callebaut semi-sweet chocolate chips generously folded into a rich, buttery dough. Baked to golden perfection — crispy at the edges but soft and chewy in the center, just as a great chocolate chip cookie should be. Made with simple, wholesome ingredients: butter, flour, eggs, vanilla extract, and a touch of sea salt that perfectly balances the sweetness. No artificial flavors or preservatives. Resealable bag to keep them fresh. 12 cookies per pack.', sku: 'BKR-COOK-CHOC-180G', weight: 180 },
            { name: 'New York Bagel Original 4pcs', description: 'Authentic New York-style bagels, hand-rolled, kettle-boiled in water with a touch of barley malt syrup (the secret to the classic bagel\'s signature chewy exterior and shiny crust), and then oven-baked to golden perfection. The result is a dense, chewy, and deeply satisfying bagel that stands apart from soft, bread-like imposters. These plain / original bagels are the ideal canvas for classic toppings: cream cheese, lox, avocado, or eggs Benedict. Pack of 4 bagels. Can be frozen and toasted directly from frozen.', sku: 'BKR-BAGL-NYOR-4PCS', weight: 400 },
            { name: 'Gardenia Blueberry Muffin 6pcs', description: 'Moist and tender blueberry muffins packed with real blueberries in every bite. Each muffin has a golden, domed top with a slightly crispy edge that gives way to a soft, tender crumb bursting with juicy blueberry pockets. The muffins are lightly sweetened so the natural tartness of the blueberries can shine through. Baked fresh and vacuum-sealed to maintain moisture and freshness. No artificial colors or flavors. Perfect for breakfast on the go, an afternoon snack, or a light dessert. Pack of 6 individually wrapped muffins.', sku: 'BKR-MUFN-BLUB-6PCS', weight: 480 },
            { name: 'Levain Sourdough Bread 400g', description: 'Artisan sourdough boule from Levain Bakery, made using a traditional 72-hour cold fermentation process with a live wild yeast starter that is maintained and fed daily. The long, slow fermentation breaks down gluten and phytic acid, making this sourdough significantly more digestible and nutritionally available than conventional breads. The thick, crackling crust is achieved through high-temperature steam baking, while the interior has a characteristic open, airy crumb with a signature mild tanginess. Pairs beautifully with good butter, olive oil, or cheese.', sku: 'BKR-SRDO-LEVN-400G', weight: 400 },
            { name: 'JCO Glazed Donut 2pcs', description: 'Signature JCO-style glazed donuts — light, airy yeast donuts with a perfectly thin, crystal-white icing glaze that shatters slightly as you bite through it. The dough is enriched with eggs and butter, giving it a brioche-like tenderness, and is fried to a pale golden color to maintain a delicate flavor. The glaze is applied while the donuts are still warm so it seeps slightly into the surface. A classic indulgence enjoyed by all ages. Two donuts per pack. Best enjoyed fresh on the day of purchase; reheat for 10 seconds in a microwave to refresh.', sku: 'BKR-DNUT-GLZD-2PCS', weight: 120 },
            { name: 'Brownies Coklat Premium 200g', description: 'Indulgent premium chocolate brownies made from a recipe that balances the richness of dark couverture chocolate with the sweetness of brown sugar and a splash of vanilla extract. These brownies have a gloriously fudgy, dense interior and a thin, paper-like crackle top — the holy grail of brownie texture. Made with real dark chocolate (60% cacao), cocoa powder, butter, eggs, and flour — no shortening, no artificial flavors, no waxy coating chocolate. Cut into generous squares. Keep in an airtight container at room temperature; best within 3 days of baking.', sku: 'BKR-BWNS-CKLT-200G', weight: 200 },
        ],
        'Beverages': [
            { name: 'Tropicana Slim OJ No Pulp 1L', description: 'Tropicana Slim Original No Pulp Orange Juice — made from 100% pure, cold-pressed oranges with no added water, sugar, or artificial preservatives. Unlike orange drinks or concentrates, Tropicana presses real oranges and never adds anything back that wasn\'t in the original fruit. Each glass delivers 100% of your daily vitamin C requirement and significant amounts of potassium, thiamine, and folate. The "no pulp" variety is filtered for a perfectly smooth, clean texture. Best served chilled. Shake well before use. Refrigerate after opening; consume within 7 days.', sku: 'BVG-OJUC-TRPC-1LTR', weight: 1050 },
            { name: 'Kapal Api Gold Coffee 380g', description: 'Kapal Api Gold — Indonesia\'s best-selling premium ground coffee blend, with a rich heritage spanning over 90 years. This signature blend combines selected Robusta and Arabica beans from the finest coffee-producing regions of Indonesia, roasted and blended to achieve the perfect balance of deep aroma, full body, and satisfying bitterness with a long, pleasant finish. Ground to the ideal consistency for traditional brewing in a cezve, drip filter, or French press. Makes approximately 190 cups. Store in a cool, dry place after opening; reseal tightly.', sku: 'BVG-GRND-KPLA-380G', weight: 380 },
            { name: 'Twinings Green Tea Jasmine 25 Bags', description: 'Twinings Jasmine Green Tea — an exquisite blend of high-quality Chinese green tea leaves gently scented with the fragrance of fresh jasmine blossoms using a traditional layering process where tea and flowers are alternated over multiple nights. The result is a tea with a clean, delicate floral aroma and a light, refreshing taste with the characteristic grassy notes of green tea and none of the bitterness. Rich in catechins and L-theanine. Brew with water at 75-80°C for 1-2 minutes. 25 individually wrapped pyramid bags.', sku: 'BVG-GRTJ-TWIN-25BG', weight: 50 },
            { name: 'Sprite Lemon-Lime Soda 1.5L', description: 'Sprite Lemon-Lime flavored carbonated soft drink in a large 1.5-litre bottle — the ultimate refreshing drink for gatherings and family occasions. Made with Sprite\'s signature blend of crisp, natural citrus flavors and sparkling carbonation. Serve ice-cold for the most refreshing experience. Sprite\'s clean, tart lemon-lime flavor and clear color make it an excellent mixer for mocktails and cocktails as well as a standalone thirst-quencher. No caffeine. Available in a resealable bottle — once opened, store in the refrigerator and consume within 3 days.', sku: 'BVG-SODA-SPRT-15LT', weight: 1500 },
            { name: 'Le Minerale Sparkling Water 750ml', description: 'Le Minerale Premium Sparkling Mineral Water, naturally sourced from the protected springs of Citeureup, West Java. The water travels through layers of volcanic rock over hundreds of years, absorbing a unique mineral profile including calcium, magnesium, and bicarbonate, which gives it its naturally refreshing taste and slight alkalinity. Lightly carbonated with fine, persistent bubbles for an elegant drinking experience. No artificial additives. The 750ml glass bottle is perfect for dining, ideal for pairing with food or simply as a sophisticated everyday hydration choice.', sku: 'BVG-SPKW-LEMN-750M', weight: 800 },
            { name: 'Ultra Milk Chocolate 250ml', description: 'Ultra Milk Full Cream Chocolate Milk in a convenient 250ml pack — the iconic chocolate milk loved by generations of Indonesian families. Made with fresh, high-quality full cream milk blended with rich cocoa powder and just the right amount of sweetness, Ultra Milk Chocolate provides all the nutritional benefits of fresh milk (calcium, protein, vitamin D, B vitamins) in a delicious form that even picky children enjoy. Processed using UHT technology for extended shelf life without refrigeration until opened. Serve chilled for the best taste.', sku: 'BVG-CHML-ULTR-250M', weight: 260 },
            { name: 'Pocari Sweat Ion Drink 500ml', description: 'Pocari Sweat Isotonic Ion Drink — a scientifically formulated sports drink designed to replenish the electrolytes (sodium, potassium, calcium, magnesium, chloride) lost through sweat during physical activity. Unlike water alone, Pocari Sweat\'s ion composition closely mimics the electrolyte balance of your body\'s fluids, enabling faster and more efficient rehydration at the cellular level. With a mild, lightly sweet flavor that is not overwhelming, it is easy to drink during and after exercise, illness with fever, or hot weather. 500ml bottle.', sku: 'BVG-ISTN-POCR-500M', weight: 520 },
            { name: 'Sosro Botol Teh Manis 500ml', description: 'Sosro Botol — original brewed sweet iced tea in the iconic glass bottle, made by Sosro, the pioneer of ready-to-drink bottled tea in Indonesia since 1974. Brewed from genuine Javanese tea leaves and sweetened with cane sugar, Sosro Botol has a distinctive, authentically familiar flavor profile — comfortably sweet, with a light tannic finish and clean, refreshing sensation that no other brand has quite replicated. Free of artificial flavors and colors. A cultural icon of Indonesia served everywhere from warungs to restaurants. Best consumed chilled.', sku: 'BVG-ICTE-SOSO-500M', weight: 530 },
        ],
        'Snacks': [
            { name: 'Lay\'s Classic Potato Chips 100g', description: 'Lay\'s Classic Potato Chips — the world\'s most iconic snack, made from thinly sliced potatoes, cooked in sunflower oil, and seasoned with perfectly balanced sea salt. Each chip is golden, uniformly thin, and has a satisfying crunch that\'s universally irresistible. Lay\'s uses a unique potato selection process to ensure consistent texture and flavor in every bag. The simplicity of three ingredients — potato, oil, and salt — allows the natural flavor of the potato to be the star. Perfect for snacking on their own or pairing with dips. 100g sharing bag.', sku: 'SNK-PTCH-LAYS-100G', weight: 100 },
            { name: 'Cadbury Dairy Milk Chocolate Bar 130g', description: 'Cadbury Dairy Milk — arguably the world\'s most beloved milk chocolate, made with a glass and a half of fresh liquid milk in every 200g. The signature Cadbury formula creates a chocolate that is distinctly smooth, creamier, and slightly softer than continental-style chocolates, with a dominant milk note balanced by just enough cocoa depth. Made with sustainably sourced cocoa as part of the Cocoa Life program. This 130g bar is broken into individual segments for easy sharing or portioning. A timeless treat for celebrations, gifts, or everyday indulgence.', sku: 'SNK-MCHC-CDBY-130G', weight: 130 },
            { name: 'Pop Corn Caramel Act II 85g', description: 'Act II Butter Popcorn — the cinema-experience popcorn at home. Ready to microwave in just 2 minutes and 30 seconds, these kernels are carefully selected for their explosion rate and hull thickness to produce large, fluffy pops with minimal unpopped kernels (old maids). The butter flavoring is applied as a light, even coating that distributes throughout the bag during popping. Made with non-GMO corn. Each microwave bag makes approximately 8 cups of popped corn — the ideal size for personal movie watching or sharing with a friend.', sku: 'SNK-PCRN-ATII-085G', weight: 85 },
            { name: 'Planters Mix Nuts Deluxe 150g', description: 'Planters Deluxe Mixed Nuts — a premium selection of cashews, almonds, macadamias, Brazil nuts, and pecans, roasted to perfection and lightly seasoned with sea salt. This deluxe blend contains no peanuts and features a higher proportion of premium tree nuts than budget nut mixes. Tree nuts are among the most nutritionally dense snacks: high in healthy monounsaturated fats, vitamin E, magnesium, selenium, and plant-based protein. Studies consistently associate regular tree nut consumption with improved cardiovascular health. Resealable canister, 150g.', sku: 'SNK-MXNT-PLNT-150G', weight: 150 },
            { name: 'Nature Valley Granola Bar Oats & Honey 42g', description: 'Nature Valley Crunchy Granola Bars in Oats \'n Honey — made with 100% whole grain rolled oats, real honey, and a touch of brown sugar, baked until crunchy and golden. These bars have an incredibly satisfying crunch that sets them apart from soft, chewy granola bars. Whole grain oats provide a sustained energy release through complex carbohydrates and beta-glucan fiber. No artificial colors, flavors, or preservatives. A convenient, portable snack that provides a wholesome energy boost before or after exercise, during commutes, or as a between-meal pick-me-up. Pack of 2 bars, 42g total.', sku: 'SNK-GRBL-NVLY-042G', weight: 42 },
            { name: 'Rold Gold Classic Pretzel Twists 200g', description: 'Rold Gold Classic Pretzel Twists — America\'s best-selling pretzel brand. These traditional hard pretzels are made with a simple, time-honored recipe: flour, water, yeast, and a pretzel solution (lye or baking soda) bath before baking that creates the characteristic mahogany-brown color, glossy surface, and distinctive slightly alkaline, slightly malty flavor. Lightly salted with coarse kosher sea salt crystals. Crunchy, low in fat, and completely satisfying. Great for dipping in mustard, cream cheese, hummus, or chocolate, or eating straight from the bag. 200g sharing bag.', sku: 'SNK-PRTZ-RLDG-200G', weight: 200 },
            { name: 'Yupi Gummy Candy Assorted 100g', description: 'Yupi Assorted Gummy Candy — colorful, chewy gummy candies in a fun mix of shapes including gummy bears, cola bottles, fried eggs, and rings, each with a distinct fruity flavor (strawberry, cherry, apple, peach, orange, and watermelon). Made with real fruit juice coloring where possible, with a delightfully springy, chewy texture that kids and adults both love. Not too sweet, not too sour — just right. Perfect for sharing at parties, as movie snacks, or as a reward treat. 100g resealable bag.', sku: 'SNK-GUMM-YUPI-100G', weight: 100 },
            { name: 'Quaker Rice Cakes Plain 100g', description: 'Quaker Plain Rice Cakes — a light, airy, and wholesome low-calorie snack made from puffed whole grain rice. Each cake has a gentle crunch and a mild, neutral flavor that makes it an incredibly versatile snack base. At just 35 calories per cake with 0g saturated fat, they are the ideal guilt-free base for both sweet and savory toppings: natural almond butter with banana, hummus with cucumber, avocado with sea salt, or cream cheese with smoked salmon. Also wonderful eaten plain for simple, clean snacking. No artificial flavors or colors. 100g bag.', sku: 'SNK-RCKC-QAKR-100G', weight: 100 },
        ],
        'Frozen Foods': [
            { name: 'Dr. Oetker Ristorante Mozzarella Pizza 335g', description: 'Dr. Oetker Ristorante Mozzarella Pizza — Germany\'s premium thin-crust frozen pizza that has won international acclaim for its restaur-quality taste straight from your home oven. The ultra-thin stone-baked base is the foundation of this pizza\'s excellence: crispy throughout with no soggy center. Topped generously with a rich, slow-cooked tomato sauce, premium mozzarella that browns and bubbles beautifully, creamy ricotta dollops, and fragrant basil. A trusted weeknight dinner or an impressive last-minute entertaining option. Bake directly from frozen at 220°C for 10-12 minutes.', sku: 'FZN-PIZA-DROZ-335G', weight: 335 },
            { name: 'Walls Magnum Classic Ice Cream 3pcs', description: 'Magnum Classic — the world\'s original premium ice cream bar on a stick. Thick, velvety Belgian chocolate couverture (cracking into satisfying shards as you bite) wraps around a smooth, delicate vanilla ice cream made with real Madagascan vanilla pod seeds. The chocolate coating is made with over 116 cocoa beans per bar. Magnum single-handedly elevated the ice cream bar category when it launched in 1989 and has maintained its position as the premium choice for adult ice cream pleasure. Three bars per pack, individually wrapped.', sku: 'FZN-ICBR-MGCL-3PCS', weight: 270 },
            { name: 'McCain Mixed Vegetables 500g', description: 'McCain Premium Frozen Mixed Vegetables — a convenient, nutritious blend of sweet corn kernels, diced carrots, green peas, and green beans, blanched at peak freshness immediately after harvest and frozen within hours using individually quick-frozen (IQF) technology. IQF preserves each individual piece separately rather than in a block, ensuring maximum nutritional retention, vibrant color, and perfect texture upon cooking — research shows that frozen vegetables often retain more nutrients than fresh produce that has been stored for several days. No added salt or preservatives. 500g.', sku: 'FZN-VEGM-MCCN-500G', weight: 500 },
            { name: 'Driscoll\'s Frozen Mixed Berries 400g', description: 'Premium Frozen Mixed Berries from Driscoll\'s — containing strawberries, blueberries, raspberries, and blackberries, all individually quick-frozen (IQF) at peak season ripeness for ideal flavor and maximum antioxidant content. Research shows that frozen berries often contain higher levels of anthocyanins and other polyphenols than out-of-season fresh berries. Perfect for blending into smoothies, making overnight chia puddings, cooking into compotes for pancakes and waffles, topping yogurt and oatmeal, or baking into muffins, crumbles, and cheesecakes. No added sugar. 400g resealable bag.', sku: 'FZN-BYMX-DRSC-400G', weight: 400 },
            { name: 'Healthy Choice Chicken Steam Meal 300g', description: 'Healthy Choice Chicken & Vegetables Steam-in-Bag Meal — a convenient, calorie-controlled complete meal that cooks directly in its specially designed steam bag in just 4-5 minutes in the microwave. This nutritiously balanced meal features tender grilled chicken breast, brown rice, and a colorful medley of vegetables in a light herb sauce. Under 350 calories per serving, under 10g of fat, and high in protein. No MSG, no artificial colors, no preservatives. Suitable for meal preppers, busy professionals, and anyone seeking a quick yet nutritious lunch or dinner. Ready in 5 minutes.', sku: 'FZN-MEAL-HCHY-300G', weight: 300 },
            { name: 'Gorton\'s Battered Cod Fillet 400g', description: 'Gorton\'s Classic Battered Cod Fillets — whole fillets of wild-caught Pacific cod encased in a light, crispy golden batter that achieves a satisfying crunch when oven-baked or air-fried without deep frying. Cod is a premium white fish prized for its large, meaty flakes, mild flavor, and high protein content. Wild-caught in the MSC Certified sustainable fisheries of the North Pacific. Each fillet is individually IQF-frozen for easy portioning. Bake from frozen at 200°C for 20-25 minutes or air-fry at 180°C for 12 minutes. Perfect with chips, tartare sauce, and mushy peas.', sku: 'FZN-FISH-GRTN-400G', weight: 400 },
            { name: 'Kellogg\'s Eggo Buttermilk Waffles 6pcs', description: 'Kellogg\'s Eggo Original Buttermilk Frozen Waffles — the iconic "L\'Eggo my Eggo" waffles that generations of Americans, and now international families, have grown up eating for breakfast. Made with real buttermilk for a characteristic slight tang and exceptional tenderness, they toast up in your toaster in about 2 minutes to a perfect golden-crisp exterior with a soft, airy honeycomb interior. Ready to top with maple syrup, fresh berries, whipped cream, or peanut butter. A quick, warm, and satisfying breakfast for busy school mornings. Pack of 6 waffle portions, individually frozen.', sku: 'FZN-WAFL-KLEG-6PCS', weight: 280 },
            { name: 'McCain Straight Cut Fries 750g', description: 'McCain Straight Cut Oven Fries — made from whole, premium Idaho-style Russet potatoes, cut into consistent straight strips and parboiled, then lightly sprayed with a touch of sunflower oil before being individually quick-frozen. These fries achieve a genuinely crispy exterior and fluffy interior when oven-baked at 220°C for 20 minutes — no deep frying required. Made from real potatoes with nothing artificial: no artificial colors, flavors, or preservatives, and just a light seasoning of sea salt. Suitable for vegans. A reliable family favorite. 750g large value bag.', sku: 'FZN-FRYZ-MCCN-750G', weight: 750 },
        ],
        'Canned Goods': [
            { name: 'Hunts Diced Tomatoes No Salt 400g', description: 'Hunt\'s Diced Tomatoes No Salt Added — vine-ripened tomatoes picked at the peak of their growing season and canned within hours of harvest, preserving their fresh-cooked flavor and maximizing nutritional value. These tomatoes are one of the best sources of lycopene, a powerful carotenoid antioxidant associated with reduced risk of cardiovascular disease and certain cancers; lycopene is actually more bioavailable from cooked or processed tomatoes than from raw. The no-salt-added formula allows you to control the sodium in your cooking. The perfect base for pasta sauces, soups, stews, salsas, and braises.', sku: 'CAN-TOMT-HUNT-400G', weight: 400 },
            { name: 'La Sierra Black Beans 400g', description: 'La Sierra Premium Black Beans in brine — traditionally cultivated black beans (frijoles negros) cooked and canned to perfectly tender perfection while retaining their deep ebony color, creamy interior, and earthy, slightly mushroom-like flavor. Black beans are a nutritional powerhouse: a single 100g serving provides approximately 8g of fiber and 9g of protein, making them one of the most filling and nutritious plant-based proteins available. Also rich in folate, magnesium, iron, and antioxidant anthocyanins. Ready to eat: rinse and drain for salads, burritos, rice dishes, or soups.', sku: 'CAN-BLKB-LASI-400G', weight: 400 },
            { name: 'Campbell\'s Chicken Noodle Soup 305g', description: 'Campbell\'s Classic Chicken Noodle Soup — the world\'s most recognizable comfort food in a can. Made from a recipe that has barely changed since 1934, this iconic soup contains tender pieces of chicken, hearty egg noodles, carrots, and celery in a savory, golden chicken broth that warms from the inside out. Generations have relied on Campbell\'s for comfort during illness, cold weather, or simply a quick, nourishing meal. Just add one can of water (or milk for a creamier result), heat for 5 minutes, and serve. Excellent as a base for homemade chicken soup. 305g (serves 2).', sku: 'CAN-SOUP-CAMP-305G', weight: 305 },
            { name: 'Chicken of the Sea Chunk Light Tuna 140g', description: 'Chicken of the Sea Chunk Light Tuna packed in water — made from 100% wild-caught skipjack tuna, the variety with the lowest mercury content of commercially canned tunas. This canned tuna is among the most protein-efficient foods available: over 30g of complete protein per 100g serving, with minimal fat. Also rich in omega-3 fatty acids, selenium, vitamin D, and vitamin B12. The chunk light style provides substantial pieces of tuna that hold their texture well in salads, sandwiches, pasta, and casseroles. Packed in spring water (not oil) for a lighter, lower-calorie option.', sku: 'CAN-TUNA-CSEA-140G', weight: 140 },
            { name: 'Del Monte Sweet Corn Whole Kernel 340g', description: 'Del Monte Sweet Corn Whole Kernel — crisp, golden sweet corn kernels harvested at the peak of their natural sweetness and canned in their own liquid to lock in flavor and freshness. Del Monte\'s rigorous quality standards ensure that only the finest corn makes it into the can. Sweet corn is a source of lutein and zeaxanthin, carotenoids associated with eye health, as well as fiber, vitamin C, thiamine, and niacin. Ready to eat: simply drain and rinse. Excellent in salads, as a side dish, added to soups and chowders, mixed into cornbread batter, or folded into a quesadilla.', sku: 'CAN-CORN-DLMT-340G', weight: 340 },
            { name: 'Del Monte Green Peas 400g', description: 'Del Monte Petit Pois Green Peas — the tiny, young, tender variety of green pea that is sweeter and more delicate than standard garden peas. Harvested at the ideal stage of maturity and immediately blanched and canned to preserve their vivid color, soft texture, and natural sweetness. Green peas are surprisingly nutritious: a good source of plant-based protein (5g per 100g), fiber, vitamin K, vitamin C, thiamine, and folate. Their mild, sweet flavor makes them one of the most universally liked vegetables. Perfect in rice dishes nasi goreng, pasta, risottos, soups, pot pies, or simply as a side.', sku: 'CAN-GRNP-DLMT-400G', weight: 400 },
            { name: 'Dole Sliced Peaches in Syrup 424g', description: 'Dole Sliced Yellow Cling Peaches in Light Syrup — carefully selected yellow cling peaches, sliced and canned in a delicate light syrup that preserves their natural sweetness and tender, juicy texture year-round regardless of season. Yellow cling peaches have firmer, denser flesh than freestone varieties, making them ideal for canning as they hold their shape beautifully. A versatile pantry staple: use as a topping for yogurt, ice cream, and crêpes, incorporate into upside-down cakes and cobblers, serve alongside cured meats such as prosciutto and ham, or blend into smoothies. Refrigerate unused portion.', sku: 'CAN-FRTC-DOLE-424G', weight: 424 },
            { name: 'Goya Black Olives Sliced 340g', description: 'Goya Sliced Black (Ripe) Olives — made from Mission variety olives harvested when naturally ripe, then cured in a gentle lactic acid brine and canned to a mild, tender consistency. Unlike briny green olives or intensely flavored Kalamatas, these mild black olives have a soft texture and subtle, slightly earthy flavor that doesn\'t overpower other ingredients, making them extraordinarily versatile. A classic pizza topping, essential in tapenade, wonderful on flatbreads and focaccia, in pasta salads, quesadillas, grain bowls, and mezze platters. Drain and rinse before use. BPA-free can.', sku: 'CAN-OLIV-GOYA-340G', weight: 340 },
        ],
        'Spices & Herbs': [
            { name: 'McCormick Black Pepper Ground 50g', description: 'McCormick Pure Ground Black Pepper — the world\'s most widely used spice, made from the dried drupes of the Piper nigrum vine. McCormick sources its black pepper from premium growing regions including Vietnam, India, and Indonesia, selecting berries at the optimal stage of maturity for the ideal balance of heat (from piperine), aroma (from terpenes), and slight earthy sweetness. Ground to a consistent medium-fine texture that distributes evenly throughout food. Piperine also has the remarkable property of dramatically increasing the bioavailability of certain nutrients, particularly curcumin from turmeric. A kitchen essential in virtually every cuisine on earth.', sku: 'SPH-BLKP-MCRM-050G', weight: 50 },
            { name: 'Indofood Bumbu Tabur Bawang Putih 45g', description: 'Indofood Garlic Powder Seasoning (Bumbu Tabur Bawang Putih) — finely ground dehydrated garlic, manufactured by Indonesia\'s largest food company using a proprietary drying process that captures the fresh garlic\'s natural allicin compounds and aromatic flavor in a convenient powder form. More stable and longer-lasting than fresh garlic, garlic powder is preferred in applications where a smooth texture is required or when fresh garlic isn\'t available. 1/8 teaspoon garlic powder equals approximately one fresh garlic clove. A staple in Indonesian pantries and essential in marinades, rubs, soups, and stir-fries. 45g.', sku: 'SPH-GRCP-INDF-045G', weight: 45 },
            { name: 'McCormick Ground Cinnamon 35g', description: 'McCormick Saigon Ground Cinnamon — made from the aromatic bark of Cinnamomum loureirii trees grown in Vietnam, world-renowned for producing the most intensely flavored cinnamon available with the highest essential oil content (up to 5%) and a notably spicier, sweeter, more complex profile than common ceylon or cassia cinnamon. The key phenolic compound cinnamaldehyde is responsible for both its distinctive flavor and its documented health properties, including supporting healthy blood sugar response. Essential in Indonesian kue-kue, chai tea, oatmeal, French toast, apple crumble, and countless international baking applications.', sku: 'SPH-CINN-MCRM-035G', weight: 35 },
            { name: 'Schwartz Dried Basil Leaves 10g', description: 'Schwartz Premium Dried Basil Leaves — made from Ocimum basilicum (sweet or Genovese basil), the quintessential herb of Italian and Mediterranean cooking, carefully harvested at peak flavor, air-dried, and sealed in a freshness-preserving glass jar to maintain its green color and fragrant volatile oils for longer than plastic packaging. The gentle drying process preserves basil\'s characteristic anise-like, peppery, clove-infused aroma. Essential in pizza sauces, Caprese salad (if using dried in off-season), pesto, pasta e fagioli, minestrone, and Neapolitan-style tomato sauces. 10g glass jar.', sku: 'SPH-BASL-SCHW-010G', weight: 10 },
            { name: 'McCormick Dried Oregano 12g', description: 'McCormick Culinary Dried Oregano Leaves — made from Origanum vulgare, a robust Mediterranean herb with a warm, slightly bitter, intensely aromatic flavor with notes of earthiness and pepper. Oregano is one of the most studied culinary herbs for its bioactive compounds: it contains carvacrol and thymol, both of which have demonstrated antimicrobial and antifungal properties in research. The dried form is approximately four times as intense as fresh, so use sparingly. An indispensable herb in Italian, Greek, Turkish, and Mexican cuisines — pizza and pasta sauce, moussaka, souvlaki, chimichurri, and taco seasoning. 12g.', sku: 'SPH-ORGN-MCRM-012G', weight: 12 },
            { name: 'Simply Organic Smoked Paprika 77g', description: 'Simply Organic Smoked Sweet Paprika — a premium certified organic spice made from select varieties of deep red capsicum (Capsicum annuum) peppers, grown, harvested, naturally dried over aromatic oak wood fires in the La Vera region of Spain, and then finely ground. The traditional oak smoking process infuses the paprika with a complex, deep campfire smokiness that distinguishes it from regular sweet or hot paprika. Rich in capsanthin and other carotenoids responsible for its intense crimson color. Adds depth to paellas, chorizo, deviled eggs, hummus, roasted vegetables, and meat rubs. Certified USDA Organic, non-GMO. 77g glass jar.', sku: 'SPH-PPKA-SMOR-077G', weight: 77 },
            { name: 'McCormick Ground Cumin 45g', description: 'McCormick Ground Cumin — made from the seeds of Cuminum cyminum, an ancient spice that is one of the most widely consumed spices in the world after pepper. Cumin has a distinctively warm, earthy, slightly lemony and bitter flavor that is the backbone of numerous spice blends including garam masala, baharat, ras el hanout, and taco seasoning. It is particularly dominant in Indian curries, Middle Eastern foods, Mexican and Tex-Mex cooking, and Ethiopian berbere. Ground cumin is more intense than whole seed and disperses evenly in dishes. Contains the antioxidant cuminaldehyde and is a source of iron. 45g.', sku: 'SPH-CUMM-MCRM-045G', weight: 45 },
            { name: 'Schwartz Dried Thyme Leaves 12g', description: 'Schwartz Premium Dried Thyme Leaves — sourced from Thymus vulgaris, a Mediterranean perennial herb in the mint family with a distinctively savory, slightly floral, earthy, and faintly minty flavor profile. Thyme is one of the most versatile culinary herbs: it pairs exceptionally well with meats, poultry, fish, and vegetables because its earthy, resinous quality adds depth without overpowering other flavors. The key aromatic compound thymol also possesses well-documented antimicrobial properties. In Indonesian cooking, thyme adds depth to European-inspired dishes. Essential for French herbes de Provence, bouquet garni, roast chicken, and braised lamb. 12g.', sku: 'SPH-THYM-SCHW-012G', weight: 12 },
        ],
        'Breakfast': [
            { name: 'Kellogg\'s Corn Flakes Original 500g', description: 'Kellogg\'s Original Corn Flakes — the original breakfast cereal that started it all, invented by Dr. John Harvey Kellogg in 1894. These golden, delicately crispy flakes are made from milled corn and are lightly sweetened for a clean, neutral flavor that pairs beautifully with cold milk and fresh fruit. Fortified with 8 essential vitamins and minerals including iron, thiamine, riboflavin, niacin, folic acid, and vitamins B6, B12, and D. Low in fat and calories when served with skimmed milk. The classic benchmark breakfast cereal enjoyed in over 180 countries. 500g pack.', sku: 'BRK-CRNF-KELG-500G', weight: 500 },
            { name: 'Quaker Instant Oatmeal Original 800g', description: 'Quaker Original Instant Oatmeal — made from 100% whole grain rolled oats that are the world\'s most studied food for their extraordinary cardiovascular and cholesterol-management benefits. Quaker was the first brand to demonstrate that oats\' soluble fiber (beta-glucan) can lower LDL ("bad") cholesterol when consumed as part of a low-saturated-fat diet — a claim now endorsed by health authorities worldwide. Cook in 90 seconds in the microwave or 3 minutes on the stovetop. Customize with your choice of toppings: banana slices, honey, nut butter, cinnamon, or berries. No added sugar in this unflavored original version. 800g pack.', sku: 'BRK-OTML-QAKR-800G', weight: 800 },
            { name: 'Bisquick Complete Pancake Mix 320g', description: 'Bisquick Complete Pancake & Waffle Mix — the original all-in-one mix that has graced American breakfast tables since 1931. Bisquick Complete already contains all-purpose enriched flour, leavening agents, and a touch of salt, so all you add is water for incredibly fluffy, golden pancakes or crispy, golden waffles in minutes. The proprietary blend of raising agents ensures a consistent, reliable rise for light, pillowy pancakes every single time. Also works brilliantly for quick dinner drop biscuits, dumplings, cinnamon rolls, and coffee cake. 320g box makes approximately 24 pancakes.', sku: 'BRK-PNCM-BISQ-320G', weight: 320 },
            { name: 'Nature\'s Bakery Fig Bar Oat & Honey 57g', description: 'Nature\'s Bakery Fig & Oat Bar — a wholesome, satisfying whole-wheat bar with a generous filling of real mission figs sweetened with a touch of honey. Made from non-GMO whole wheat flour and real fruit (figs are one of the highest-fiber fruits available), these bars are a conscientiously clean breakfast and snack option free from high-fructose corn syrup, artificial flavors, and preservatives. Each twin-pack (2 bars, 57g) provides sustained energy from complex carbohydrates and fiber. Vegan and certified Kosher. Peanut-free. Ideal for school bags and office desks.', sku: 'BRK-FIGB-NABK-057G', weight: 57 },
            { name: 'Tropicana Strawberry Jam 340g', description: 'Tropicana Premium Strawberry Jam — made with a generous proportion of real strawberries slow-cooked with cane sugar and a squeeze of lemon juice (a natural pectin activator and preservative) in small batches to achieve the ideal set and a jam that tastes unmistakably of real strawberries, not strawberry flavoring. The jewel-red color and luscious fruit-forward sweetness with a pleasantly bright acidity distinguish this jam from mass-produced varieties made primarily with glucose syrup and minimal fruit. Spread generously on toast, croissants, scones, and crumpets, or stir into yogurt. 340g glass jar.', sku: 'BRK-JAMW-TRPC-340G', weight: 340 },
            { name: 'New Zealand Manuka Honey 250g', description: 'Certified New Zealand Monofloral Manuka Honey UMF 10+ — sourced exclusively from the nectar of the wild Leptospermum scoparium (manuka) bush that grows in the remote, unpolluted wilderness of New Zealand and southeastern Australia. The UMF (Unique Manuka Factor) grading certifies the concentration of methylglyoxal (MGO), the key bioactive compound responsible for manuka honey\'s extraordinary antibacterial properties not found in any other honey. At UMF 10+ / MGO 263+, this honey represents a therapeutic-grade product with independently verified potency. Consume raw by the spoonful, stir into warm (not hot) beverages, or apply topically to minor wounds. 250g.', sku: 'BRK-HNYW-MNUK-250G', weight: 250 },
            { name: 'Quaker Maple Brown Sugar Oatmeal 8pcs', description: 'Quaker Instant Oatmeal Maple & Brown Sugar — the best-selling flavored instant oatmeal in the world, combining the hearty goodness of 100% whole grain rolled oats with the irresistible combination of warm maple syrup flavor and sweet caramelized brown sugar. Ready in just 60-90 seconds with hot water or milk, this oatmeal dissolves into a creamy, comforting bowl that\'s warm, sweet, and deeply satisfying on cold mornings. Made from whole grain oats providing 3g of soluble beta-glucan fiber per serving. No artificial colors or flavors. Pack of 8 single-serving sachets (43g each).', sku: 'BRK-OTFV-MPLB-8PCS', weight: 344 },
            { name: 'Johnsonville Original Breakfast Sausage Links 340g', description: 'Johnsonville Original Breakfast Sausage Links — made in Wisconsin from premium cuts of pork seasoned with Johnsonville\'s proprietary blend of spices, herbs, and subtle maple sweetness in a natural pork casing. Each sausage link has a distinctive spiral coil from hand-linking and browns to a beautiful mahogany color in the pan with an audibly satisfying sizzle. The natural casing provides a firm, snappy bite that distinguishes these from mass-produced processed sausages. Perfect alongside eggs and pancakes in a classic American breakfast spread. Pan-fry over medium heat for 12-15 minutes, turning occasionally. Pack of 12 links, 340g.', sku: 'BRK-SSGP-JOHN-340G', weight: 340 },
        ],
        'Household': [
            { name: 'Sunlight Lemon Fresh Dish Soap 800ml', description: 'Sunlight Lemon Fresh Concentrated Dish Soap — Indonesia\'s most trusted dishwashing liquid, powered by Sunlight\'s advanced Active Grease-cutting formula. The concentrated surfactant system cuts through even the most stubborn grease, baked-on food residue, and oily film on pans and plates in a single wipe, without needing to scrub. The fresh lemon fragrance infused with tiny droplets of real lemon extract leaves dishes smelling clean and your hands feeling refreshed (enriched with conditioning agents for hand care). Safe for all types of dishware including non-stick and crystal glass. Refill-compatible pump bottle. 800ml.', sku: 'HHD-DSWL-SNLT-800M', weight: 820 },
            { name: 'Attack Easy Liquid Laundry Detergent 1.5L', description: 'Attack Easy Liquid Laundry Detergent — a premium concentrated formula designed to work effectively in both cold and warm water, in standard and high-efficiency (HE) washing machines, and by hand. Powered by Attack\'s Bio-Enzyme Action, this detergent breaks down and lifts protein stains (blood, egg, grass), oil stains (grease, sebum), and food stains from fabric fibers with far less mechanical scrubbing required. Leaves clothes with a fresh, clean floral fragrance that is long-lasting but not cloying. Phosphate-free and biodegradable surfactants. Gentle enough for regular wash, powerful enough for heavily soiled work clothes. 1.5L.', sku: 'HHD-LDTG-ATTK-15LT', weight: 1550 },
            { name: 'Paseo Bamboo Paper Towels 3 Rolls', description: 'Paseo Bambook Premium 2-ply Paper Towels — triple pack made from sustainable bamboo fibers, a material that grows up to 35 times faster than the hardwood trees used in conventional paper towels and can be harvested without killing the plant. Despite being an eco-friendly option, these towels have a soft yet durable texture and superior absorbency compared to many conventional paper towels, capable of holding up to 11 times their own weight in liquid. The perforated sheets are larger than standard sizes. Each roll contains 60 sheets. BPA-free, unbleached, no artificial fragrances. Triple roll pack.', sku: 'HHD-PTWL-PSEO-3RLL', weight: 450 },
            { name: 'Paseo Soft Toilet Paper 12 Rolls', description: 'Paseo Soft Toilet Tissue 3-ply — a premium 12-roll multipack of 3-ply toilet tissue made from FSC-certified sustainably sourced virgin wood pulp. Three separate ply of tissue are embossed together to create a soft, pillowy feel that is gentle on sensitive skin while maintaining structural integrity when wet. The unique micro-emboss pattern increases thickness perception and soft tactile quality. Fragrance-free. Each roll contains 200 sheets, each sheet measuring approximately 10cm × 10cm. Resealable outer plastic bag for convenient storage. Suitable for all standard toilet roll holders. Septic-safe formula.', sku: 'HHD-TOTP-PSEO-12RL', weight: 1200 },
            { name: 'Oxo Good Grips Heavy Duty Trash Bags 30pcs', description: 'OXO Good Grips Heavy-Duty Drawstring Trash Bags, 30 litre capacity — engineered with the same thoughtful design philosophy as OXO\'s kitchen tools. These bags are constructed from triple-layer "force-flex" polyethylene that stretches and recovers rather than tearing when subjected to sharp or heavy loads, allowing you to fill them fuller and more confidently. The double-gripper drawstring ties securely and the trailing cord locks to prevent accidental loosening during carry. Star-shaped base seals evenly distribute weight. Odor Shield technology embedded in the material neutralizes common garbage odors for up to 5 days. 30 bags per roll.', sku: 'HHD-TRBG-OXOG-030P', weight: 600 },
            { name: 'Mr. Muscle All-Purpose Cleaner Trigger 500ml', description: 'Mr. Muscle Advanced Power Multi-Surface Spray Cleaner — a single bottle that effectively cleans and disinfects hard surfaces throughout the home: kitchen benchtops, stovetops, sinks, bathroom tiles, toilet exteriors, mirrors, and windows. The advanced formula cuts through grease and food residue in the kitchen while killing 99.9% of bacteria on contact (including E. coli and Staphylococcus aureus) on non-porous surfaces and leaving a streak-free shine on glass and mirrors. Leaves a subtle, clean citrus-and-mint fragrance. Ergonomic trigger sprayer for comfortable extended use. 500ml.', sku: 'HHD-APCS-MRMG-500M', weight: 520 },
            { name: ' 3M Scotch-Brite Kitchen Sponge 3pcs', description: '3M Scotch-Brite Non-Scratch Scrub Sponge — the original that defines the entire category, trusted by professional chefs and home cooks alike for over 50 years. Each sponge combines two functional materials in one: a soft, highly absorbent cellulose fiber sponge on one side for applying soap and wiping surfaces, and the iconic green Scotch-Brite nylon scrub pad on the reverse for removing stuck-on food, grease, and residue. The "Non-Scratch" certification means it is safe for use on non-stick coatings, delicate china, and enamelware. Withstands 30+ wash cycles before replacement. Pack of 3 sponges.', sku: 'HHD-SPON-3SCB-003P', weight: 90 },
            { name: 'Tessa Premium 3-ply Facial Tissues 200pcs', description: 'Tessa Premium 3-Ply Facial Tissues — a luxuriously soft facial tissue made from triple-ply virgin pulp that provides the ultimate combination of softness, strength, and thickness. Designed specifically for face and nose use, these tissues are hypoallergenic, dermatologically tested, and free from optical brighteners, inks, and fragrances that can irritate sensitive facial skin. The 3-ply construction means they do not tear or disintegrate when used to blow or wipe your nose. Each tissue fully biodegrades without releasing microplastics. 200-sheet box with a tear-less dispensing perforation. Ideal for bedroom, bathroom, and desk.', sku: 'HHD-FCTC-TSSA-200P', weight: 350 },
        ],
        'Personal Care': [
            { name: 'Pantene Pro-V Repair & Protect Shampoo 480ml', description: 'Pantene Pro-V Repair & Protect Shampoo — powered by the exclusive Pro-Vitamin B5 (panthenol) formula that penetrates into the hair cortex to repair damage from the inside out, not just coat the surface. Specifically designed for color-treated, chemically processed, heat-styled, or mechanically damaged hair, this shampoo actively rebuilds broken keratin protein bonds through its amino acid-enriched formula. After just 2-3 weeks of use, clinical studies demonstrate measurably stronger, less breakage-prone hair with a significantly smoother surface cuticle and enhanced luster. Lathers richly for thorough scalp cleansing. 480ml bottle with flip-top cap.', sku: 'PRC-SHMP-PNTN-480M', weight: 500 },
            { name: 'Pepsodent Action 123 Toothpaste 190g', description: 'Pepsodent Action 123 Fluoride Toothpaste — Indonesia\'s most widely used toothpaste, providing tri-action oral care: (1) removes plaque through Micro-Granules that gently polish tooth surfaces without damaging enamel, (2) whitens teeth progressively through optical brightening agents and enamel polish, and (3) protects against cavities with the clinically proven 1450ppm sodium fluoride concentration that remineralizes enamel and inhibits acid-producing bacteria. Freshens breath with a clean, refreshing spearmint flavor. Recommended by the Indonesian Dental Association. 190g tube. Use twice daily.', sku: 'PRC-TPST-PEPS-190G', weight: 190 },
            { name: 'Dove Deep Moisture Body Wash 390ml', description: 'Dove Deep Moisture Body Wash — formulated with Dove\'s breakthrough NutriumMoisture technology, micro-droplets of moisturizing cream that deposit onto the skin during washing, unlike conventional shower gels which merely promise moisturizing benefits that are entirely rinsed away. Studies demonstrate that Dove Deep Moisture Body Wash provides 24-hour skin hydration in a single shower — proven in dermatological testing with even significantly dry skin types. The light, clean, and comforting fragrance of white peach and Jasmine lingers gently after rinsing. pH-balanced and hypoallergenic. Contains no parabens. 390ml pump bottle.', sku: 'PRC-BDWH-DOVE-390M', weight: 400 },
            { name: 'Rexona Men Sport Defence Deodorant 150ml', description: 'Rexona Men Sport Defence Aerosol Antiperspirant Deodorant — developed in partnership with athletes for the demands of high-intensity physical activity. The MotionSense technology responds to the movement and friction of your body, activating and releasing fresh fragrance precisely when your body is working hardest and producing the most odor-causing sweat. Clinical studies demonstrate 72-hour sweat and odor protection even under sustained intense exercise conditions. Alcohol-free formula that won\'t damage or discolor clothing. The Sport Defence fragrance is a clean, energizing blend of fresh citrus, aquatic notes, and a warm woody base. 150ml pressurized aerosol.', sku: 'PRC-DEOM-REXN-150M', weight: 165 },
            { name: 'Cetaphil Gentle Skin Cleanser 500ml', description: 'Cetaphil Gentle Skin Cleanser — the dermatologist-developed, dermatologist-prescribed cleanser that has been trusted by sensitive skin patients for over 70 years. Unlike most cleansers that achieve their cleaning action through detergents and foaming agents (often the cause of skin stripping and irritation), Cetaphil uses a uniquely gentle, non-foaming formulation based on glycerin, niacinamide, and carefully selected non-irritating surfactants that remove dirt, oil, and makeup without disrupting the skin\'s critical moisture barrier. Clinically proven safe for newborns, eczema, rosacea, psoriasis, and post-procedure skin. Fragrance-free, paraben-free, non-comedogenic. 500ml pump.', sku: 'PRC-FCCL-CTPL-500M', weight: 520 },
            { name: 'Dettol Antibacterial Hand Soap 250ml', description: 'Dettol Original Antibacterial Liquid Hand Soap — the gold standard in household germ protection, trusted by hospitals and recommended by the WHO Hand Hygiene Initiative. The clinically proven formula kills 99.9% of bacteria on contact (including E. coli, Staphylococcus aureus, and Salmonella) in the 20 seconds of normal handwashing. Unlike hand sanitizers that merely inhibit bacteria, this soap physically lifts and removes microorganisms from the skin surface with water. Enriched with moisturizing agents to prevent the drying associated with frequent handwashing. The distinctive pine needle fragrance signals cleanliness effectively. Family-safe; suitable for frequent daily use. 250ml.', sku: 'PRC-HNSP-DTTL-250M', weight: 260 },
            { name: 'Gillette Series Sensitive Shaving Cream 200ml', description: 'Gillette Series Triple Protection Shaving Cream for Sensitive Skin — specially formulated to address the unique challenges of shaving sensitive skin, which is more susceptible to razor burn, nicks, redness, and post-shave irritation. The cream\'s exceptionally rich, dense lather provides a protective cushion between the blade and skin, allowing the razor to glide with minimal resistance. Enriched with aloe vera extract and vitamin E to soothe and protect. The formula is free of alcohol, artificial dyes, and potential irritants designated on the EU sensitizer watchlist. Dermatologically tested, pH-balanced. Compatible with all safety and cartridge razors. 200ml pressurized aerosol.', sku: 'PRC-SHCM-GILT-200M', weight: 215 },
            { name: 'Neutrogena Hydro Boost Moisturizer 50ml', description: 'Neutrogena Hydro Boost Water Gel Moisturizer — the product that defined the "water gel" moisturizer category when it launched. The lightweight, oil-free gel texture instantly absorbs into skin without a trace of greasiness, making it a universal formula suitable for all skin types including oily and combination skin that cannot tolerate traditional cream moisturizers. The hero ingredient is hyaluronic acid (100mg per bottle), a molecular "water magnet" capable of attracting and holding up to 1000 times its own weight in water within the skin matrix. Clinically proven to increase skin hydration by 80% in the first hour and maintain elevated hydration levels for 24 hours. 50ml air-tight pump.', sku: 'PRC-MSTR-NTRG-050M', weight: 55 },
        ],
    }

    private async findRandomCategory() {
        const count = await prisma.product_categories.count()
        if (count === 0) return null

        const skip = Math.floor(Math.random() * count)

        return prisma.product_categories.findFirst({
            skip,
            select: { id: true, name: true }
        })
    }

    public create = async () => {
        // Get random category
        const category = await this.findRandomCategory()
        if (!category) throw new Error('Cannot create product without category')

        // Get products for this category
        const categoryProducts = this.productsByCategory[category.name as keyof typeof this.productsByCategory]
        if (!categoryProducts) throw new Error(`No products defined for category: ${category.name}`)

        // Select random product from category
        const productData = faker.helpers.arrayElement(categoryProducts)

        // Generate slug
        let slugName = productData.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

        // Ensure slug uniqueness
        const existingBySlug = await prisma.products.findUnique({ where: { slugName } })
        if (existingBySlug) {
            slugName = `${slugName}-${faker.string.alphanumeric(5).toLowerCase()}`
        }

        // Ensure SKU uniqueness
        let sku = productData.sku
        const existingBySku = await prisma.products.findUnique({ where: { sku } })
        if (existingBySku) {
            sku = `${sku}-${faker.string.alphanumeric(4).toUpperCase()}`
        }

        // Generate random price between 5,000 and 150,000 IDR
        const basePrice = faker.number.float({ min: 5000, max: 150000, fractionDigits: 0 })

        return prisma.products.create({
            data: {
                id: faker.string.uuid(),
                productName: productData.name,
                slugName,
                description: productData.description,
                sku,
                weight: productData.weight,
                categoryId: category.id,
                basePrice,
                createdAt: faker.date.past({ years: 1 }),
            },
        })
    }

    public createMany = async (count: number) => {
        const createdProducts = []
        for (let i = 0; i < count; i++) {
            const product = await this.create()
            createdProducts.push(product)
        }
        return createdProducts
    }
}

export default ProductsFactory
