import { EmployeeRole } from "@prisma/client"

export const minShippingCostSeed: number = 10000
export const maxShippingCostSeed: number = 30000 
export const minQuantityItemSelectedSeed: number = 1
export const maxQuantityItemSelectedSeed: number = 10
export const minDiscountFactorSeed: number = 0.8
export const maxDiscountFactorSeed: number = 1.0
export const oldestPeriodYears: number = 1 

export const userSeedData = [
    // Admins
    {
        email: 'kimgeovedi@gmail.com',
        username: 'kimgeovedi',
        role: 'ADMIN' as const,
        employee: {
            fullName: 'Kim Geovedi',
            role: EmployeeRole.SUPER_ADMIN,
            branchCity: 'Yogyakarta',
        },
        addresses: [
            {
                label: 'Rumah',
                type: 'Rumah',
                receiptName: 'Kim Geovedi',
                notes: 'Belakang masjid',
                phone: '081200000001',
                address: 'Jl. Malioboro No. 55, Yogyakarta',
                lat: -7.7928,
                long: 110.3657,
                isPrimary: true,
            },
            {
                label: 'Kampus',
                type: 'Lainnya',
                receiptName: 'Kim Geovedi',
                notes: 'Gedung fakultas teknik',
                phone: '081200000002',
                address: 'Universitas Gadjah Mada, Yogyakarta',
                lat: -7.7714,
                long: 110.3778,
                isPrimary: false,
            },
            {
                label: 'Kos',
                type: 'Rumah',
                receiptName: 'Kim Geovedi',
                notes: 'Pagar merah nomor 3',
                phone: '081200000003',
                address: 'Jl. Kaliurang KM 5, Sleman, Yogyakarta',
                lat: -7.7543,
                long: 110.3870,
                isPrimary: false,
            },
        ],
    },      
    {
        email: 'arif.dwiyanto@gmail.com',
        username: 'arif.dwiyanto',
        role: 'ADMIN' as const,
        employee: {
            fullName: 'Arif Dwiyanto',
            role: EmployeeRole.STORE_ADMIN,
            branchCity: 'Bandung',
        },
        addresses: [
            {
                label: 'Rumah',
                type: 'Rumah',
                receiptName: 'Arif Dwiyanto',
                notes: 'Pagar hitam',
                phone: '081200000004',
                address: 'Jl. Merdeka No. 10, Bandung',
                lat: -6.9175,
                long: 107.6191,
                isPrimary: true,
            },
            {
                label: 'Kantor',
                type: 'Kantor',
                receiptName: 'Arif Dwiyanto',
                notes: 'Lantai 5',
                phone: '081200000005',
                address: 'Jl. Asia Afrika No. 1, Bandung',
                lat: -6.9211,
                long: 107.6108,
                isPrimary: false,
            },
            {
                label: 'Kos',
                type: 'Rumah',
                receiptName: 'Arif Dwiyanto',
                notes: 'Kamar 2B',
                phone: '081200000006',
                address: 'Jl. Dago No. 55, Bandung',
                lat: -6.8951,
                long: 107.6101,
                isPrimary: false,
            },
        ],
    },
    {
        email: 'flazen.work@gmail.com',
        username: 'flazen.work',
        role: 'ADMIN' as const,
        employee: {
            fullName: 'Flazen Work',
            role: EmployeeRole.STORE_ADMIN,
            branchCity: 'Jakarta Selatan',
        },
        addresses: [
            {
                label: 'Rumah',
                type: 'Rumah',
                receiptName: 'Flazen Work',
                notes: 'Dekat lampu merah',
                phone: '081200000007',
                address: 'Jl. Fatmawati No. 30, Jakarta Selatan',
                lat: -6.2983,
                long: 106.7942,
                isPrimary: true,
            },
            {
                label: 'Kantor',
                type: 'Kantor',
                receiptName: 'Flazen Work',
                notes: 'Lobby utama',
                phone: '081200000008',
                address: 'Jl. Gatot Subroto No. 99, Jakarta Selatan',
                lat: -6.2355,
                long: 106.8271,
                isPrimary: false,
            },
            {
                label: 'Apartemen',
                type: 'Rumah',
                receiptName: 'Flazen Work',
                notes: 'Unit 8C tower 2',
                phone: '081200000009',
                address: 'Apartemen Mediterania, Jakarta Barat',
                lat: -6.1751,
                long: 106.8650,
                isPrimary: false,
            },
        ],
    },
    // Customers
    {
        email: 'flazen.edu@gmail.com',
        username: 'flazen.edu',
        role: 'CUSTOMER' as const,
        addresses: [
            {
                label: 'Apartemen',
                type: 'Rumah',
                receiptName: 'Flazen Edu',
                notes: 'Unit 12A',
                phone: '081200000010',
                address: 'Apartemen Mediterania, Jakarta Barat',
                lat: -6.1751,
                long: 106.8650,
                isPrimary: true,
            },
            {
                label: 'Kampus',
                type: 'Lainnya',
                receiptName: 'Flazen Edu',
                notes: 'Gedung rektorat',
                phone: '081200000011',
                address: 'Universitas Indonesia, Depok',
                lat: -6.3607,
                long: 106.8268,
                isPrimary: false,
            },
            {
                label: 'Rumah Ortu',
                type: 'Rumah',
                receiptName: 'Flazen Edu',
                notes: 'Cat tembok kuning',
                phone: '081200000012',
                address: 'Jl. Kebon Jeruk No. 5, Jakarta Barat',
                lat: -6.1901,
                long: 106.7794,
                isPrimary: false,
            },
        ],
    },
    {
        email: 'tester_customer_jkt@gmail.com',
        username: 'tester_jkt',
        role: 'CUSTOMER' as const,
        addresses: [
            {
                label: 'Rumah',
                type: 'Rumah',
                receiptName: 'Tester Jakarta',
                notes: 'Dekat lampu merah',
                phone: '081200000013',
                address: 'Jl. Fatmawati No. 30, Jakarta Selatan',
                lat: -6.2983,
                long: 106.7942,
                isPrimary: true,
            },
            {
                label: 'Kantor',
                type: 'Kantor',
                receiptName: 'Tester Jakarta',
                notes: 'Lobby utama',
                phone: '081200000014',
                address: 'Jl. Gatot Subroto No. 99, Jakarta Selatan',
                lat: -6.2355,
                long: 106.8271,
                isPrimary: false,
            },
            {
                label: 'Gym',
                type: 'Lainnya',
                receiptName: 'Tester Jakarta',
                notes: 'Titipkan ke resepsionis',
                phone: '081200000015',
                address: 'Jl. Kemang Raya No. 12, Jakarta Selatan',
                lat: -6.2617,
                long: 106.8139,
                isPrimary: false,
            },
        ],
    },
    {
        email: 'tester_customer_bdg@gmail.com',
        username: 'tester_bdg',
        role: 'CUSTOMER' as const,
        addresses: [
            {
                label: 'Rumah',
                type: 'Rumah',
                receiptName: 'Tester Bandung',
                notes: 'Depan warung bu Tini',
                phone: '081200000016',
                address: 'Jl. Cihampelas No. 100, Bandung',
                lat: -6.9005,
                long: 107.6087,
                isPrimary: true,
            },
            {
                label: 'Kantor',
                type: 'Kantor',
                receiptName: 'Tester Bandung',
                notes: 'Lantai 4 ruang marketing',
                phone: '081200000017',
                address: 'Jl. Soekarno Hatta No. 456, Bandung',
                lat: -6.9474,
                long: 107.6395,
                isPrimary: false,
            },
            {
                label: 'Kos',
                type: 'Rumah',
                receiptName: 'Tester Bandung',
                notes: 'Kamar paling ujung',
                phone: '081200000018',
                address: 'Jl. Tubagus Ismail No. 7, Bandung',
                lat: -6.8873,
                long: 107.6143,
                isPrimary: false,
            },
        ],
    },
    {
        email: 'tester_customer_diy@gmail.com',
        username: 'tester_diy',
        role: 'CUSTOMER' as const,
        addresses: [
            {
                label: 'Rumah',
                type: 'Rumah',
                receiptName: 'Tester Jogja',
                notes: 'Belakang masjid',
                phone: '081200000019',
                address: 'Jl. Malioboro No. 55, Yogyakarta',
                lat: -7.7928,
                long: 110.3657,
                isPrimary: true,
            },
            {
                label: 'Kampus',
                type: 'Lainnya',
                receiptName: 'Tester Jogja',
                notes: 'Gedung fakultas teknik',
                phone: '081200000020',
                address: 'Universitas Gadjah Mada, Yogyakarta',
                lat: -7.7714,
                long: 110.3778,
                isPrimary: false,
            },
            {
                label: 'Kos',
                type: 'Rumah',
                receiptName: 'Tester Jogja',
                notes: 'Pagar merah nomor 3',
                phone: '081200000021',
                address: 'Jl. Kaliurang KM 5, Sleman, Yogyakarta',
                lat: -7.7543,
                long: 110.3870,
                isPrimary: false,
            },
        ],
    },
]